# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_breeds_dogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeds',
            name='exerciseneeds',
            field=models.IntegerField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='breeds',
            name='friendliness',
            field=models.IntegerField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='breeds',
            name='sheddingamount',
            field=models.IntegerField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='breeds',
            name='trainability',
            field=models.IntegerField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='age',
            field=models.IntegerField(max_length=100),
        ),
    ]
